version: '3.4'
services:
  mrcli.local:
    build: .
    image: danielpieper/mrcli-go:latest
    volumes:
      - cache:/go/pkg/mod/cache
      - $PWD:/build
    container_name: mrcli-go.local

  # gitlab.local:
  #   image: 'gitlab/gitlab-ce:latest'
  #   restart: always
  #   hostname: 'gitlab.local'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'http://gitlab.local:8929'
  #       gitlab_rails['gitlab_shell_ssh_port'] = 2224
  #   ports:
  #     - '8929:8929'
  #     - '2224:22'
  #   volumes:
  #     - gitlab-config:/etc/gitlab
  #     - gitlab-logs:/var/log/gitlab
  #     - gitlab-data:/var/opt/gitlab

volumes:
  cache:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
